#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds001226-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001226-fmriprep/.reproman/jobs/local/20220420-004705-6e2d/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001226-fmriprep/.reproman/jobs/local/20220420-004705-6e2d/stderr

#SBATCH --nodes=9
#SBATCH --ntasks=36
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds001226-fmriprep/.reproman/jobs/local/20220420-004705-6e2d

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 35); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun